import java.util.Random;

public class RandomUserData {

        private String firstName[] = {
                        "Tessa",
                        "Karilynn",
                        "Valenka",
                        "Antoinette",
                        "Aliza",
                        "Sergeant",
                        "Hew",
                        "Arin",
                        "Miltie",
                        "Sigismondo",
                        "Rafaello",
                        "Valina",
                        "Vilhelmina",
                        "Lynsey",
                        "Fedora",
                        "Judah",
                        "Analise",
                        "Hewe",
                        "Tomaso",
                        "Halsy",
                        "Jaquenette",
                        "Wylma",
                        "Shepherd",
                        "Sheelagh",
                        "Dennie",
                        "Bevan",
                        "Heddi",
                        "Temp",
                        "Allard",
                        "Averill",
                        "Aubine",
                        "Johnnie",
                        "Flin",
                        "Phillida",
                        "Lowrance",
                        "Ethelin",
                        "Idell",
                        "Hattie",
                        "Rowena",
                        "Diena",
                        "Lay",
                        "Hillary",
                        "Edsel",
                        "Daryn",
                        "Hillary",
                        "Evie",
                        "Valentine",
                        "Allegra",
                        "Monah",
                        "Hulda",
                        "Ryon",
                        "Babb",
                        "Kessia",
                        "Gayla",
                        "Astrix",
                        "Charmine",
                        "Ania",
                        "Elvera",
                        "Kelila",
                        "Annabal",
                        "Demetris",
                        "Ilka",
                        "Cecelia",
                        "Orville",
                        "Dusty",
                        "Joelynn",
                        "Alyce",
                        "Tova",
                        "Bella",
                        "Almira",
                        "Marin",
                        "Bronson",
                        "Napoleon",
                        "Nev",
                        "Essa",
                        "Cassandra",
                        "Elita",
                        "Carmine",
                        "Chester",
                        "Maxy",
                        "Codie",
                        "Myles",
                        "Alva",
                        "Winnie",
                        "Andonis",
                        "Randi",
                        "Grata",
                        "Shelley",
                        "Gram",
                        "Teriann",
                        "Niel",
                        "Crysta",
                        "Martha",
                        "Selestina",
                        "Nikolas",
                        "Jehu",
                        "Jereme",
                        "Sidney",
                        "Saree",
                        "Nessi"
        };

        private String lastName[] = {
                        "MacMoyer",
                        "Stringfellow",
                        "Hellen",
                        "Lemmers",
                        "Goldspink",
                        "Von Der Empten",
                        "Atwater",
                        "Shord",
                        "Souch",
                        "Wardlaw",
                        "Granham",
                        "Betteson",
                        "Viney",
                        "Sustin",
                        "Dunks",
                        "O'Reagan",
                        "Shinton",
                        "Guyonneau",
                        "Saltrese",
                        "Madine",
                        "Lembke",
                        "Worvill",
                        "Paulton",
                        "Titchener",
                        "Borrowman",
                        "Yankov",
                        "Guyet",
                        "Kolakowski",
                        "Cloonan",
                        "Studdert",
                        "Knox",
                        "Figgs",
                        "Giraudeau",
                        "Presdie",
                        "Floyed",
                        "Howlett",
                        "Janauschek",
                        "Starrs",
                        "Sever",
                        "Ollerenshaw",
                        "Beaston",
                        "Arnecke",
                        "Wasbrough",
                        "Shone",
                        "Harbage",
                        "Beddingham",
                        "Francis",
                        "Pardie",
                        "Cheeseman",
                        "Roubay",
                        "Mollitt",
                        "Sarfati",
                        "Copnall",
                        "Shenfisch",
                        "Tows",
                        "Tivenan",
                        "Thurley",
                        "Mapledoram",
                        "McRamsey",
                        "McLeish",
                        "Postlewhite",
                        "Garvagh",
                        "Tabram",
                        "Danelet",
                        "Mounter",
                        "Vannoort",
                        "Derisly",
                        "Corey",
                        "Hamflett",
                        "Jansey",
                        "Bursell",
                        "Winkless",
                        "Edgerly",
                        "Mathiasen",
                        "Baudts",
                        "Perillo",
                        "Costall",
                        "Beaglehole",
                        "Soughton",
                        "Ilchuk",
                        "Brummell",
                        "Collumbell",
                        "Newing",
                        "McGairl",
                        "Faley",
                        "Klauber",
                        "Schumacher",
                        "Garham",
                        "Hilliam",
                        "Beckinsale",
                        "Camier",
                        "Goghin",
                        "Bubeer",
                        "Elcomb",
                        "Falkous",
                        "Seczyk",
                        "Marciek",
                        "Rubee",
                        "Zanioletti",
                        "Barter"
        };

        String religions[] = { "Muslim", "Hindu", "Buddhist", "Sikh", "Jews", "Christian" };

        String languages[] = {
                        "English",
                        "Azeri",
                        "Georgian",
                        "Finnish",
                        "Moldovan",
                        "Irish Gaelic",
                        "Thai",
                        "Malagasy",
                        "Greek",
                        "Lithuanian",
                        "Somali",
                        "Danish",
                        "Nepali",
                        "Hungarian",
                        "Tamil",
                        "Kazakh",
                        "Tok Pisin",
                        "Dutch",
                        "Fijian",
                        "Montenegrin",
                        "Bulgarian",
                        "Maltese",
                        "Kurdish",
                        "Swedish",
                        "German",
                        "Kyrgyz",
                        "Sotho",
                        "Estonian",
                        "French",
                        "Marathi",
                        "Indonesian",
                        "Macedonian",
                        "Hindi",
                        "Zulu",
                        "Afrikaans",
                        "Bosnian",
                        "Tetum",
                        "Italian",
                        "Oriya",
                        "Sign Language",
                        "Dzongkha",
                        "Dhivehi",
                        "Hebrew",
                        "Kashmiri",
                        "Tajik",
                        "Gujarati",
                        "Swati",
                        "Khmer",
                        "Belarusian",
                        "Czech",
                        "Arabic",
                        "Persian",
                        "Yiddish",
                        "Icelandic",
                        "Mongolian",
                        "Portuguese",
                        "Kannada",
                        "Malayalam",
                        "Māori",
                        "Tswana",
                        "Korean",
                        "Polish",
                        "Romanian"
        };

        String cities[] = {
                        "Guishan",
                        "Priupskiy",
                        "Sumqayıt",
                        "Irshava",
                        "Douniani",
                        "Jaworzynka",
                        "Malo",
                        "Anambongan",
                        "Kokoshkino",
                        "Medenychi",
                        "Puqian",
                        "Sidi Bousber",
                        "Independencia",
                        "Yamethin",
                        "Milíkov",
                        "Sukorejo",
                        "Al ‘Ulá",
                        "Wudangshan",
                        "Oebobo",
                        "Klinan",
                        "Radnice",
                        "Butungan",
                        "Melfort",
                        "Uppsala",
                        "Mucifal",
                        "Yanggu’ao",
                        "Ossora",
                        "Las Flores",
                        "Benghazi",
                        "San Francisco",
                        "Zgornje Bitnje",
                        "Kliwon Cibingbin",
                        "Tatou",
                        "Genova",
                        "Jinnan",
                        "Taoyuan",
                        "Yuxi",
                        "Weepangali",
                        "Kachug",
                        "Tucupita",
                        "Mayisad",
                        "Diamantina",
                        "Uchkeken",
                        "Sosnovka",
                        "Bearna",
                        "Hwasun",
                        "Bluefields",
                        "Santo Domingo",
                        "Laiyang",
                        "Carleton Place",
                        "Ribeiro",
                        "Louisville",
                        "Hats’avan",
                        "Saboyá",
                        "Randusari",
                        "El Corozal",
                        "Uthai Thani",
                        "Caherconlish",
                        "Zoushi",
                        "Artur Nogueira",
                        "Mizusawa",
                        "Zhaozhen",
                        "Basiao",
                        "Cibenda",
                        "Huangjin",
                        "Södertälje",
                        "Kuczbork-Osada",
                        "Guanxi",
                        "Jarānwāla",
                        "Qaryat al Qābil",
                        "Kasserine",
                        "Clarence-Rockland",
                        "Chonogol",
                        "Chirpan",
                        "Jonquière",
                        "Ouyang",
                        "Kněžpole",
                        "Tongzhong",
                        "Oslo",
                        "Wangge’ertang",
                        "Pericik",
                        "Gonayiv",
                        "Fonte de Angeão",
                        "Pangawaren",
                        "Suwaru",
                        "Taozhuang",
                        "Tianya",
                        "Luofang",
                        "Ares Tengah",
                        "Kumo",
                        "Houxixi",
                        "Donskoy",
                        "Wairiang",
                        "An Châu",
                        "Bangkok",
                        "Alepoú",
                        "Berlin",
                        "Zengji",
                        "Shkodër"
        };

        public UserData getUserData() {
                Random random = new Random();

                int randomFirstNameIdx = random.nextInt(firstName.length);
                int randomLastNameIdx = random.nextInt(lastName.length);
                int randomReligionIdx = random.nextInt(religions.length);
                int randomMotherTongueIdx = random.nextInt(languages.length);
                int randomCityIdx = random.nextInt(cities.length);

                int randomAge = random.nextInt(123);
                int randomAnnualSalary = random.nextInt(1000001 - 10000) + 10000;
                int randomNoOfVehical = random.nextInt(16);

                String name = firstName[randomFirstNameIdx] + " " + lastName[randomLastNameIdx];
                String religion = religions[randomReligionIdx];
                String mother_tongue = languages[randomMotherTongueIdx];
                String city = cities[randomCityIdx];

                UserData userdata = new UserData(name, religion, city, mother_tongue, randomAge, randomNoOfVehical,
                                randomAnnualSalary);
                random = null;
                return userdata;
        }

}